version: "2"
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
    networks:
      operating-vpcbr:
        ipv4_address: 10.6.0.2

  kafka1:
    image: wurstmeister/kafka
    ports:
      - 19092:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://10.6.0.3:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    depends_on:
      - zookeeper
    networks:
      operating-vpcbr:
        ipv4_address: 10.6.0.3

  kafka2:
    image: wurstmeister/kafka
    ports:
      - 29092:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://10.6.0.4:9092
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    depends_on:
      - zookeeper
    networks:
      operating-vpcbr:
        ipv4_address: 10.6.0.4

  kafka3:
    image: wurstmeister/kafka
    ports:
      - 39092:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://10.6.0.5:9092
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    depends_on:
      - zookeeper
    networks:
      operating-vpcbr:
        ipv4_address: 10.6.0.5

networks:
  operating-vpcbr:
      driver: bridge
      ipam:
        config:
          - subnet: 10.6.0.0/16
            gateway: 10.6.0.1
