version: "2"
services:
  zookeeper1:
    hostname: zookeeper1
    image: zookeeper
    ports:
      - 12181:2181
    environment:      
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    networks:
      intro-vpcbr:
        ipv4_address: 10.2.0.2
  zookeeper2:
    hostname: zookeeper2
    image: zookeeper
    ports:
      - 22181:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    networks:
      intro-vpcbr:
        ipv4_address: 10.2.0.3
  zookeeper3:
    hostname: zookeeper3
    image: zookeeper
    ports:
      - 32181:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888,server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    networks:
      intro-vpcbr:
        ipv4_address: 10.2.0.4

  kafka1:
    image: wurstmeister/kafka
    ports:
      - 19092:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://10.2.0.5:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181, zookeeper2:2181, zookeeper3:2181
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      intro-vpcbr:
        ipv4_address: 10.2.0.5

  kafka2:
    image: wurstmeister/kafka
    ports:
      - 29092:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://10.2.0.6:9092
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181, zookeeper2:2181, zookeeper3:2181
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      intro-vpcbr:
        ipv4_address: 10.2.0.6

  kafka3:
    image: wurstmeister/kafka
    ports:
      - 39092:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://10.2.0.7:9092
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181, zookeeper2:2181, zookeeper3:2181
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      intro-vpcbr:
        ipv4_address: 10.2.0.7

networks:
  intro-vpcbr:
      driver: bridge
      ipam:
        config:
          - subnet: 10.2.0.0/16
            gateway: 10.2.0.1
